// import type { Metadata } from "next";
// import { Provider } from "@/components/shared/provider";
// import "./globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body>
//         <Provider>{children}</Provider>
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Provider } from "@/components/shared/provider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Lush & Luxe Beauty Salon",
  description: "Luxury beauty salon services.",
  icons: {
    icon: "/favicon.ico", // Standard browsers
    shortcut: "/favicon.ico", // Windows / old browsers
    apple: "/apple-touch-icon.png", // iOS support (if available)
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}

